apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - riskgame.ga
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - riskgame.ga
