apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: risk-main
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: risk-main
    spec:
      containers:
        - name: risk-main
          imagePullPolicy: Always
          image: riskreg.azurecr.io/risk-main:latest
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: risk-main
spec:
  type: LoadBalancer
  ports:
    - port: 9000
  selector:
    app: risk-main
